security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, makkers]
        in_memory:
            memory:
                users:
                    baker:
                        password: $2y$12$6HIeI43WciOnZ.AAAY5EieUzWJRHwrJN/4jY8F745AdTLOxJAyIkS
                        roles: 'ROLE_BAKER'
        makkers:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: false
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/create-upcoming-bake, roles: ROLE_BAKER }
        - { path: ^/, roles: ROLE_MAKKER }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_BAKER: ROLE_MAKKER
